### ISSUE TITLE
Issue with resources folder

### ISSUE THREAD

**Issue by bskrt** [amandaghassaei/Fusion360-Design-History-Animation#1]
Fusion crashed on line [442](https://github.com/amandaghassaei/Fusion360-Design-History-Animation/blob/b19d372f03dba6ab8eca9579ed19a7678ec80fa1/Design-History-Animation/Design-History-Animation.py#L442) for me:

`'./resources/') # relative resource file path is specified `

Removing the resources parameter altogether fixed it on my part.
Thought I'd share.

Very cool script btw!

**Comment by amandaghassaei** [comment]
Fixed at https://github.com/amandaghassaei/Fusion360-Design-History-Animation/commit/51b4a546830f80abb3e07df12177225093be4154

Thanks for letting me know - I had an empty folder in there that wasn't being committed!
