### ISSUE TITLE
Adding different zoom levels 

### ISSUE THREAD

**Issue by Relativiteit** [amandaghassaei/Fusion360-Design-History-Animation#4]
Add the ability to change zoom levels for the Design Version Time lapse. 

example:
- Until extrusion X gets performed zoom at 50 % (for overall view) switch to 200 % zoom. 

Acceptance criteria: 
- Ability to specify at what point in the build timeline the camera zoom will change.

**Comment by amandaghassaei** [comment]
I think this is a little too specific for the scope of these scripts. I'd recommend creating two animations: one at zoom level 1 and another at zoom level 2, then cutting them together in video editing software.
