### ISSUE TITLE
Add the ability to change camera angle 

### ISSUE THREAD

**Issue by Relativiteit** [amandaghassaei/Fusion360-Design-History-Animation#5]
Add the ability to change the angle of the camera during the Design Version Timelapse.

example:
- When action Y(in timeline) is performed change camera perspective to front.

Acceptance criteria:
- Ability to change camera position based and a predetermined action chosen from the timeline. 
-

**Comment by amandaghassaei** [comment]
I think this is a little too specific for the scope of these scripts. I'd recommend creating two animations: one at camera angle 1 and another at camera angle 2, then cutting them together in video editing software.
